from datetime import datetime
from sqlalchemy import Boolean, DateTime, ForeignKey, Integer, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship
from ..database import Base
class MetaConnection(Base):
    __tablename__='meta_connections'; id: Mapped[int]=mapped_column(primary_key=True); display_name: Mapped[str]=mapped_column(String(200)); facebook_page_id: Mapped[str|None]=mapped_column(String(100)); facebook_page_name: Mapped[str|None]=mapped_column(String(200)); instagram_user_id: Mapped[str|None]=mapped_column(String(100)); instagram_username: Mapped[str|None]=mapped_column(String(200)); encrypted_user_token: Mapped[str|None]=mapped_column(Text); encrypted_page_token: Mapped[str|None]=mapped_column(Text); granted_scopes_json: Mapped[str]=mapped_column(Text,default='[]'); token_expires_at: Mapped[datetime|None]=mapped_column(DateTime); last_validated_at: Mapped[datetime|None]=mapped_column(DateTime); connection_status: Mapped[str]=mapped_column(String(30),default='NOT_CONNECTED'); created_at: Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow); updated_at: Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow,onupdate=datetime.utcnow)
class ContentItem(Base):
    __tablename__='content_items'; id: Mapped[int]=mapped_column(primary_key=True); external_id: Mapped[str]=mapped_column(String(120),unique=True,index=True); series: Mapped[str|None]=mapped_column(String(120)); title: Mapped[str|None]=mapped_column(String(300)); subtitle: Mapped[str|None]=mapped_column(String(300)); caption_default: Mapped[str|None]=mapped_column(Text); caption_facebook: Mapped[str|None]=mapped_column(Text); caption_instagram: Mapped[str|None]=mapped_column(Text); link: Mapped[str|None]=mapped_column(String(500)); alt_text: Mapped[str|None]=mapped_column(Text); notes: Mapped[str|None]=mapped_column(Text); content_status: Mapped[str]=mapped_column(String(30),default='DRAFT'); created_at: Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow); updated_at: Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow,onupdate=datetime.utcnow); assets=relationship('MediaAsset',back_populates='content',cascade='all, delete-orphan'); schedules=relationship('ScheduleEntry',back_populates='content',cascade='all, delete-orphan')
class MediaAsset(Base):
    __tablename__='media_assets'; id: Mapped[int]=mapped_column(primary_key=True); content_item_id: Mapped[int]=mapped_column(ForeignKey('content_items.id')); platform_override: Mapped[str|None]=mapped_column(String(20)); position: Mapped[int]=mapped_column(Integer,default=1); original_filename: Mapped[str]=mapped_column(String(255)); local_path: Mapped[str]=mapped_column(String(500)); normalized_path: Mapped[str|None]=mapped_column(String(500)); sha256: Mapped[str|None]=mapped_column(String(64)); mime_type: Mapped[str|None]=mapped_column(String(80)); width: Mapped[int|None]=mapped_column(Integer); height: Mapped[int|None]=mapped_column(Integer); aspect_ratio: Mapped[str|None]=mapped_column(String(30)); file_size: Mapped[int|None]=mapped_column(Integer); validation_status: Mapped[str]=mapped_column(String(20),default='VALID'); validation_messages_json: Mapped[str]=mapped_column(Text,default='[]'); remote_public_url: Mapped[str|None]=mapped_column(String(1000)); created_at: Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow); updated_at: Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow,onupdate=datetime.utcnow); content=relationship('ContentItem',back_populates='assets')
class ScheduleEntry(Base):
    __tablename__='schedule_entries'; id: Mapped[int]=mapped_column(primary_key=True); content_item_id: Mapped[int]=mapped_column(ForeignKey('content_items.id')); scheduled_at_utc: Mapped[datetime]=mapped_column(DateTime,index=True); display_timezone: Mapped[str]=mapped_column(String(50),default='Europe/Warsaw'); target_facebook: Mapped[bool]=mapped_column(Boolean,default=True); target_instagram: Mapped[bool]=mapped_column(Boolean,default=True); schedule_status: Mapped[str]=mapped_column(String(30),default='DRAFT'); approval_status: Mapped[str]=mapped_column(String(30),default='NOT_REVIEWED'); created_at: Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow); updated_at: Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow,onupdate=datetime.utcnow); content=relationship('ContentItem',back_populates='schedules'); publications=relationship('PlatformPublication',back_populates='schedule',cascade='all, delete-orphan')
class PlatformPublication(Base):
    __tablename__='platform_publications'; id: Mapped[int]=mapped_column(primary_key=True); schedule_entry_id: Mapped[int]=mapped_column(ForeignKey('schedule_entries.id')); platform: Mapped[str]=mapped_column(String(20)); publication_status: Mapped[str]=mapped_column(String(30),default='PENDING'); attempt_count: Mapped[int]=mapped_column(Integer,default=0); remote_post_id: Mapped[str|None]=mapped_column(String(200)); last_error_message: Mapped[str|None]=mapped_column(Text); idempotency_key: Mapped[str]=mapped_column(String(100),unique=True); published_at: Mapped[datetime|None]=mapped_column(DateTime); created_at: Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow); updated_at: Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow,onupdate=datetime.utcnow); schedule=relationship('ScheduleEntry',back_populates='publications')
class ImportBatch(Base):
    __tablename__='import_batches'; id: Mapped[int]=mapped_column(primary_key=True); source_filename: Mapped[str]=mapped_column(String(255)); source_type: Mapped[str]=mapped_column(String(30)); row_count: Mapped[int]=mapped_column(Integer,default=0); new_count: Mapped[int]=mapped_column(Integer,default=0); updated_count: Mapped[int]=mapped_column(Integer,default=0); skipped_count: Mapped[int]=mapped_column(Integer,default=0); error_count: Mapped[int]=mapped_column(Integer,default=0); mapping_json: Mapped[str]=mapped_column(Text,default='{}'); created_at: Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
class AuditLog(Base):
    __tablename__='audit_logs'; id: Mapped[int]=mapped_column(primary_key=True); entity_type: Mapped[str]=mapped_column(String(80)); entity_id: Mapped[str]=mapped_column(String(80)); action: Mapped[str]=mapped_column(String(80)); details_json: Mapped[str]=mapped_column(Text,default='{}'); created_at: Mapped[datetime]=mapped_column(DateTime,default=datetime.utcnow)
