import { ArrowUpRight, Check, ChevronDown } from 'lucide-react';
import { useEffect } from 'react';
import { motion } from 'motion/react';
import Seo, { SITE_URL } from './Seo';
import { trackEvent } from '../analytics';

const serviceAreas = [
  { number: '01', title: 'Audyt widoczności w AI', items: ['sprawdzenie odpowiedzi dla najważniejszych pytań klientów', 'analiza obecności marki i konkurencji', 'analiza źródeł cytowanych przez systemy AI', 'identyfikacja luk tematycznych', 'lista zapytań i obszarów do rozwoju'] },
  { number: '02', title: 'Techniczne SEO i crawlability', items: ['analiza robots.txt i sitemap.xml', 'kontrola indeksacji, canonicali i linkowania wewnętrznego', 'dostępność treści bez zbędnych barier JavaScript', 'kontrola Googlebot, Bingbot i OAI-SearchBot', 'dane strukturalne zgodne z widoczną treścią'] },
  { number: '03', title: 'Architektura treści', items: ['strony usługowe odpowiadające na konkretne problemy', 'sekcje pytań i odpowiedzi oraz słownik pojęć', 'poradniki, porównania i case studies', 'treści oparte na własnych danych i doświadczeniu', 'logiczna hierarchia nagłówków'] },
  { number: '04', title: 'Entity SEO i wiarygodność', items: ['spójne informacje o firmie i usługach', 'autorstwo oraz odpowiedzialność za treści', 'dane kontaktowe i informacje o doświadczeniu', 'realne przykłady wdrożeń', 'spójność danych na stronie i profilach zewnętrznych'] },
  { number: '05', title: 'Dane strukturalne', items: ['Organization, WebSite i Service', 'WebPage i BreadcrumbList', 'Article, Person i FAQPage, gdy odpowiadają treści', 'bez pustych ani fikcyjnych pól', 'schema.org jako opis treści, nie jako obietnica rankingu'] },
  { number: '06', title: 'Monitoring', items: ['Google Search Console i Bing Webmaster Tools', 'Google Analytics 4 oraz źródła ruchu AI', 'okresowe sprawdzanie zestawu zapytań testowych', 'monitoring zmian widoczności marki i konkurencji', 'raportowanie trendów zamiast wniosków z jednej odpowiedzi modelu'] },
];

const deliverables = ['Mapa pytań i tematów', 'Audyt widoczności marki', 'Lista problemów technicznych', 'Rekomendowana architektura treści', 'Backlog wdrożeń', 'Priorytety SEO i GEO', 'Rekomendacje danych strukturalnych', 'Plan mierzenia efektów'];
const audiences = ['Sklepy internetowe', 'Firmy B2B', 'Firmy usługowe', 'Producenci i dystrybutorzy', 'Marki posiadające specjalistyczną wiedzę', 'Firmy mające unikalne dane, produkty lub doświadczenie', 'Organizacje rozwijające ruch organiczny'];
const faqs = [
  ['Czy GEO zastępuje SEO?', 'Nie. GEO rozszerza fundamenty SEO o lepszą strukturę informacji, spójność danych o marce i treści odpowiadające na realne pytania.'],
  ['Czy można zagwarantować obecność firmy w odpowiedziach ChatGPT?', 'Nie. Żadna firma nie może zagwarantować cytowania przez konkretny model. Możemy poprawić techniczne i treściowe warunki, które zwiększają szansę odnalezienia i poprawnego zrozumienia marki.'],
  ['Jak sprawdzić, czy marka jest widoczna w AI?', 'Przygotowujemy zestaw pytań związanych z ofertą, cyklicznie sprawdzamy odpowiedzi i porównujemy obecność marki, konkurencji oraz źródeł. Pojedyncza odpowiedź nie jest jednak pełnym pomiarem.'],
  ['Czy potrzebny jest plik llms.txt?', 'Nie jest wymaganym czynnikiem rankingowym. Najpierw dbamy o crawlability, indeksację, czytelny HTML, sitemapę i dobre treści.'],
  ['Czy dane strukturalne poprawiają widoczność w AI?', 'Pomagają jednoznacznie opisać treść, gdy odpowiadają temu, co użytkownik widzi na stronie. Nie są specjalnym schema.org dla GEO ani gwarancją cytowania.'],
  ['Jak długo trwa wdrożenie GEO?', 'Zależy od stanu serwisu, liczby usług i dostępnych danych. Zaczynamy od audytu i priorytetów, a następnie dzielimy wdrożenie na konkretne etapy.'],
  ['Czy GEO ma sens dla małej firmy?', 'Tak, jeśli firma ma konkretną specjalizację, doświadczenie lub dane, które warto uporządkować i pokazać osobom szukającym rozwiązania.'],
  ['Czy optymalizujecie również istniejące treści?', 'Tak. Możemy przeanalizować istniejące strony, poprawić ich strukturę, uzupełnić brakujące odpowiedzi i połączyć je z nową architekturą informacji.'],
];

export const GEO_SCHEMA: Record<string, unknown>[] = [
  { '@context': 'https://schema.org', '@type': 'Service', name: 'Widoczność w wyszukiwarkach AI — GEO', serviceType: 'Generative Engine Optimization', provider: { '@type': 'Organization', name: 'NUSH', url: SITE_URL }, areaServed: 'Polska', url: `${SITE_URL}/widocznosc-w-ai`, description: 'Audyt GEO, architektura treści, entity SEO i techniczne wdrożenia zwiększające gotowość marki do wyszukiwania AI.' },
  { '@context': 'https://schema.org', '@type': 'WebPage', name: 'Widoczność w AI i GEO dla firm | NUSH', url: `${SITE_URL}/widocznosc-w-ai`, inLanguage: 'pl-PL' },
  { '@context': 'https://schema.org', '@type': 'BreadcrumbList', itemListElement: [{ '@type': 'ListItem', position: 1, name: 'NUSH', item: SITE_URL }, { '@type': 'ListItem', position: 2, name: 'Widoczność w AI', item: `${SITE_URL}/widocznosc-w-ai` }] },
  { '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: faqs.map(([question, answer]) => ({ '@type': 'Question', name: question, acceptedAnswer: { '@type': 'Answer', text: answer } })) },
];

export default function GeoServicePage() {
  useEffect(() => { trackEvent('geo_service_view', { page: '/widocznosc-w-ai' }); }, []);
  const handleContactStart = () => trackEvent('geo_contact_start', { location: 'geo_service_page' });

  return <>
    <Seo title="Widoczność w AI i GEO dla firm | NUSH" description="Pomagamy firmom zwiększać widoczność w Google AI Overviews, ChatGPT, Gemini, Copilot i Perplexity. Audyt GEO, architektura treści, entity SEO i techniczne wdrożenia." path="/widocznosc-w-ai" schema={GEO_SCHEMA} />
    <main>
      <section className="relative overflow-hidden border-b border-white/10 px-6 pb-24 pt-28 md:px-10 md:pb-32 md:pt-40"><div className="hero-grid pointer-events-none absolute inset-0 opacity-30" aria-hidden="true" /><div className="relative mx-auto max-w-7xl"><a href="/" className="mb-12 inline-flex items-center gap-2 font-mono text-xs uppercase tracking-widest text-white/55 hover:text-neon">← Wróć do NUSH</a><p className="font-mono text-xs font-bold uppercase tracking-[.22em] text-neon">[AI SEARCH / GEO]</p><h1 className="mt-7 max-w-6xl text-4xl font-black uppercase leading-[.95] md:text-7xl">Widoczność w wyszukiwarkach AI.<br /><span className="text-neon">Generative Engine Optimization.</span></h1><p className="mt-8 max-w-3xl text-lg leading-relaxed text-white/65 md:text-xl">Klienci coraz częściej szukają rekomendacji i odpowiedzi bezpośrednio w narzędziach AI. Pomagamy markom przygotować technologię, treści i dane tak, aby mogły być odnajdywane i przywoływane również poza klasyczną listą wyników Google.</p></div></section>
      <section className="border-b border-white/10 px-6 py-20 md:px-10 md:py-28"><div className="mx-auto max-w-4xl"><p className="font-mono text-xs font-bold uppercase tracking-widest text-neon">CZYM JEST GEO?</p><h2 className="mt-5 text-3xl font-black uppercase md:text-5xl">SEO, które rozumie nowe sposoby wyszukiwania.</h2><p className="mt-7 text-lg leading-relaxed text-white/65">Generative Engine Optimization to rozwój widoczności marki w odpowiedziach generowanych przez systemy AI. GEO nie zastępuje SEO. Rozszerza je o lepszą strukturę informacji, wiarygodne treści eksperckie, spójne dane o marce oraz przygotowanie serwisu do pracy z nowymi sposobami wyszukiwania.</p></div></section>
      <section className="border-b border-white/10 bg-[#080808] px-6 py-20 md:px-10 md:py-28"><div className="mx-auto max-w-7xl"><p className="font-mono text-xs font-bold uppercase tracking-widest text-neon">CO ROBIMY?</p><div className="mt-10 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{serviceAreas.map((area, index) => <motion.article key={area.number} initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: .12 }} transition={{ delay: index * .06 }} whileHover={{ y: -4 }} className="border border-white/10 p-6 hover:border-neon/70"><div className="border-b border-white/10 pb-5 font-mono text-2xl font-bold text-neon">{area.number}</div><h2 className="mt-6 text-xl font-black uppercase leading-tight">{area.title}</h2><ul className="mt-6 space-y-3 text-sm leading-relaxed text-white/60">{area.items.map((item) => <li key={item} className="flex gap-3"><span className="font-mono text-neon" aria-hidden="true">+</span><span>{item}</span></li>)}</ul></motion.article>)}</div></div></section>
      <section className="border-b border-white/10 px-6 py-20 md:px-10 md:py-28"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[.7fr_1.3fr]"><div><p className="font-mono text-xs font-bold uppercase tracking-widest text-neon">CO OTRZYMUJE KLIENT?</p><h2 className="mt-5 text-3xl font-black uppercase md:text-5xl">Plan, który można wdrożyć.</h2></div><ul className="grid gap-4 sm:grid-cols-2">{deliverables.map((item) => <li key={item} className="flex gap-3 border-b border-white/10 pb-4 text-base uppercase text-white/75"><Check size={18} className="shrink-0 text-neon" aria-hidden="true" />{item}</li>)}</ul></div></section>
      <section className="border-b border-white/10 bg-[#080808] px-6 py-20 md:px-10 md:py-28"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-2"><div><p className="font-mono text-xs font-bold uppercase tracking-widest text-neon">CZEGO NIE OBIECUJEMY?</p><h2 className="mt-5 text-3xl font-black uppercase md:text-5xl">Bez magicznych obietnic.</h2><p className="mt-7 max-w-2xl text-lg leading-relaxed text-white/65">Żadna firma nie może zagwarantować, że określony model AI zacytuje konkretną stronę. Możemy jednak zwiększyć szansę odnalezienia i poprawnego zrozumienia marki poprzez lepszą technologię, treści, dane i wiarygodność.</p></div><div><p className="font-mono text-xs font-bold uppercase tracking-widest text-neon">DLA KOGO?</p><ul className="mt-6 space-y-3 text-base text-white/70">{audiences.map((item) => <li key={item} className="flex gap-3"><span className="font-mono text-neon" aria-hidden="true">+</span>{item}</li>)}</ul></div></div></section>
      <section className="border-b border-white/10 px-6 py-20 md:px-10 md:py-28"><div className="mx-auto max-w-4xl"><p className="font-mono text-xs font-bold uppercase tracking-widest text-neon">FAQ / GEO</p><div className="mt-8 border-t border-white/15">{faqs.map(([question, answer]) => <details key={question} className="border-b border-white/15 py-5"><summary className="flex cursor-pointer list-none items-center justify-between gap-5 text-left text-base font-bold uppercase md:text-lg"><span>{question}</span><ChevronDown size={20} className="shrink-0 text-neon" aria-hidden="true" /></summary><p className="max-w-3xl pt-5 text-base leading-relaxed text-white/60">{answer}</p></details>)}</div></div></section>
      <section className="bg-neon px-6 py-16 text-black md:px-10 md:py-20"><div className="mx-auto flex max-w-7xl flex-col items-start justify-between gap-8 md:flex-row md:items-end"><div><p className="font-mono text-xs font-bold uppercase tracking-widest">NUSH / AI SEARCH</p><h2 className="mt-5 max-w-3xl text-3xl font-black uppercase leading-tight md:text-5xl">Sprawdźmy, czy AI wie, czym zajmuje się Twoja firma.</h2><p className="mt-5 max-w-2xl text-base leading-relaxed text-black/70">Przeanalizujemy technologię, treści i obecność marki dla pytań, które mogą prowadzić do sprzedaży.</p></div><a href="/#kontakt" onClick={handleContactStart} className="inline-flex items-center gap-3 border-2 border-black px-5 py-4 text-xs font-black uppercase transition-colors hover:bg-black hover:text-neon">Porozmawiajmy o GEO <ArrowUpRight size={17} aria-hidden="true" /></a></div></section>
      <section className="border-b border-white/10 px-6 py-10 md:px-10"><div className="mx-auto flex max-w-7xl flex-wrap gap-5 font-mono text-xs uppercase tracking-wider text-white/50"><a href="/blog/generative-engine-optimization-geo" className="hover:text-neon">Przeczytaj: Generative Engine Optimization</a><a href="/slownik#geo" className="hover:text-neon">GEO w słowniku pojęć</a></div></section>
    </main>
  </>;
}
